// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqDZdO64ACrhedeYi-lep-rcDkq6RIyXA',
    appId: '1:462741887939:web:071279d6f163bb5ddabb76',
    messagingSenderId: '462741887939',
    projectId: 'cinema-et-series-tv',
    authDomain: 'cinema-et-series-tv.firebaseapp.com',
    storageBucket: 'cinema-et-series-tv.firebasestorage.app',
    measurementId: 'G-X1F9XGW376',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbvJCc5cgbd98XjU6Mqws_cdsrY7yqFY8',
    appId: '1:462741887939:android:1f53f8fc10955b32dabb76',
    messagingSenderId: '462741887939',
    projectId: 'cinema-et-series-tv',
    storageBucket: 'cinema-et-series-tv.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvkJ6MTP3bJ09DbI2fYIbbvAfidOKvBdA',
    appId: '1:462741887939:ios:efe650d56634701edabb76',
    messagingSenderId: '462741887939',
    projectId: 'cinema-et-series-tv',
    storageBucket: 'cinema-et-series-tv.firebasestorage.app',
    iosBundleId: 'com.example.flutterProjet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvkJ6MTP3bJ09DbI2fYIbbvAfidOKvBdA',
    appId: '1:462741887939:ios:efe650d56634701edabb76',
    messagingSenderId: '462741887939',
    projectId: 'cinema-et-series-tv',
    storageBucket: 'cinema-et-series-tv.firebasestorage.app',
    iosBundleId: 'com.example.flutterProjet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqDZdO64ACrhedeYi-lep-rcDkq6RIyXA',
    appId: '1:462741887939:web:8c89d4777b0127fadabb76',
    messagingSenderId: '462741887939',
    projectId: 'cinema-et-series-tv',
    authDomain: 'cinema-et-series-tv.firebaseapp.com',
    storageBucket: 'cinema-et-series-tv.firebasestorage.app',
    measurementId: 'G-KVXZ59E1QR',
  );
}
